self_see_links:
  - name: HRP2JSKNT/LLEG-LINK0
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK1
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK2
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK3
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK4
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK5
    padding: 0.05
  - name: HRP2JSKNT/LLEG-LINK6
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK0
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK1
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK2
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK3
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK4
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK5
    padding: 0.05
  - name: HRP2JSKNT/RLEG-LINK6
    padding: 0.05
  - name: HRP2JSKNT/TORSO-LINK0
    padding: 0.05
  - name: HRP2JSKNT/TORSO-LINK1
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK0
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK1
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK2
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK3
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK4
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK5
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK6
    padding: 0.05
  - name: HRP2JSKNT/LARM-LINK7
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK0
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK1
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK2
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK3
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK4
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK5
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK6
    padding: 0.05
  - name: HRP2JSKNT/RARM-LINK7
    padding: 0.05

  